"""empty message

Revision ID: 12f16f3e3e49
Revises: f603c458f2a8
Create Date: 2017-09-15 14:14:20.853447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f16f3e3e49'
down_revision = 'f603c458f2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_constraint('bucketlists_created_by_id_fkey', 'bucketlists', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlists', 'users', ['created_by'], ['id'])
    op.drop_column('bucketlists', 'created_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.create_foreign_key('bucketlists_created_by_id_fkey', 'bucketlists', 'users', ['created_by_id'], ['id'])
    op.drop_column('bucketlists', 'created_by')
    # ### end Alembic commands ###
