"""empty message

Revision ID: 5dddc3dedd98
Revises: a68ae0b1182a
Create Date: 2017-09-14 19:21:47.788563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dddc3dedd98'
down_revision = 'a68ae0b1182a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_constraint('bucketlists_user_id_fkey', 'bucketlists', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlists', 'users', ['created_by'], ['id'])
    op.drop_column('bucketlists', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.create_foreign_key('bucketlists_user_id_fkey', 'bucketlists', 'users', ['user_id'], ['id'])
    op.drop_column('bucketlists', 'created_by')
    # ### end Alembic commands ###
