"""empty message

Revision ID: a68ae0b1182a
Revises: 1764bfb946d5
Create Date: 2017-09-11 15:33:14.327560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68ae0b1182a'
down_revision = '1764bfb946d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_column('bucketlists', 'user_id')
    # ### end Alembic commands ###
